blog_user_create:
  path: /create-account
  defaults: { _controller  : "BlogBundle:User:createUserAccount" }
  methods: [GET,POST]

blog_index:
  path: /
  defaults: { _controller  : "BlogBundle:User:createUserAccount" }
  methods: [GET,POST]